- hosts: all
  become: yes
  tasks:
    - name: remove stock docker
      apt:
        name: "{{ item }}"
        state: absent
        update_cache: false
      with_items:
        - docker.io
        - docker
        - docker-engine

    - name: install necessary apt helpers
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: install docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker apt repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: 'docker'

    - name: install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: install K8e apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes' APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: install kubelet
      apt:
        name: kubelet
        state: present
        update_cache: true

    - name: install kubeadm
      apt:
        name: kubeadm
        state: present

- hosts: master
  become: yes
  tasks:
    - name: install kubectl
      apt:
        name: kubectl
        state: present
